CREATE TABLE stats_players (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
steamid BIGINT UNSIGNED NOT NULL UNIQUE
);

CREATE TABLE stats_servers (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
server VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE stats_statistics (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
steamid_id INTEGER NOT NULL,
server_id INTEGER NOT NULL,
bleeding SMALLINT DEFAULT 0,
bones SMALLINT DEFAULT 0,
freezing SMALLINT DEFAULT 0,
burning SMALLINT DEFAULT 0,
food SMALLINT DEFAULT 0,
water SMALLINT DEFAULT 0,
zombie SMALLINT DEFAULT 0,
animal SMALLINT DEFAULT 0,
suicide SMALLINT DEFAULT 0,
infection SMALLINT DEFAULT 0,
breath SMALLINT DEFAULT 0,
vehicle SMALLINT DEFAULT 0,
shred SMALLINT DEFAULT 0,
landmine SMALLINT DEFAULT 0,
arena SMALLINT DEFAULT 0,
sentry SMALLINT DEFAULT 0,
acid SMALLINT DEFAULT 0,
boulder SMALLINT DEFAULT 0,
burner SMALLINT DEFAULT 0,
spit SMALLINT DEFAULT 0,
spark SMALLINT DEFAULT 0,
deathgun SMALLINT DEFAULT 0,
deathmelee SMALLINT DEFAULT 0,
deathpunch SMALLINT DEFAULT 0,
deathroadkill SMALLINT DEFAULT 0,
deathblownup SMALLINT DEFAULT 0,
killgun SMALLINT DEFAULT 0,
killmelee SMALLINT DEFAULT 0,
killpunch SMALLINT DEFAULT 0,
killroadkill SMALLINT DEFAULT 0,
killblownup SMALLINT DEFAULT 0,
FOREIGN KEY (steamid_id) REFERENCES stats_players(id) ON DELETE CASCADE,
FOREIGN KEY (server_id) REFERENCES stats_servers(id) ON DELETE CASCADE
);
