#!/bin/bash

declare -A typedeath

typedeath[0]='Bleeding'
typedeath[1]='Bones'
typedeath[2]='Freezing'
typedeath[3]='Burning'
typedeath[4]='Food'
typedeath[5]='Water'
typedeath[6]='Zombie'
typedeath[7]='Animal'
typedeath[8]='Suicide'
typedeath[9]='Infection'
typedeath[10]='Breath'
typedeath[11]='Vehicle'
typedeath[12]='Shred'
typedeath[13]='Landmine'
typedeath[14]='Arena'
typedeath[15]='Sentry'
typedeath[16]='Acid'
typedeath[17]='Boulder'
typedeath[18]='Burner'
typedeath[19]='Spit'
typedeath[20]='Spark'
typedeath[21]='deathGun'
typedeath[22]='deathMelee'
typedeath[23]='deathPunch'
typedeath[24]='deathRoadkill'
typedeath[25]='deathBlownup'
typedeath[26]='killGun'
typedeath[27]='killMelee'
typedeath[28]='killPunch'
typedeath[29]='killRoadkill'
typedeath[30]='killBlownup'

declare -A deathregex

deathregex[0]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] bled to death!'
deathregex[1]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] fractured to death!'
deathregex[2]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] froze to death!'
deathregex[3]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] burned to death!'
deathregex[4]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] starved to death!'
deathregex[5]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] dehydrated to death!'
deathregex[6]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] was mauled by a zombie!'
deathregex[7]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] was mauled by an animal!'
deathregex[8]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] killed themself.'
deathregex[9]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] was infected to death!'
deathregex[10]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] suffocated to death!'
deathregex[11]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] was blown up by a vehicle!'
deathregex[12]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] was shredded to bits!'
deathregex[13]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] was blown up by a landmine!'
deathregex[14]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] was eliminated by the arena!'
deathregex[15]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] was shot by a sentry gun!'
deathregex[16]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] was blown up by a zombie!'
deathregex[17]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] was crushed by a zombie!'
deathregex[18]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] was burned by a zombie!'
deathregex[19]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] was dissolved by a zombie!'
deathregex[20]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] was electrocuted by a zombie!'
deathregex[21]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] was shot in the (?:leg|arm|torso|head) by '
deathregex[22]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] was chopped in the (?:leg|arm|torso|head) by '
deathregex[23]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] was punched in the (?:leg|arm|torso|head) by '
deathregex[24]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] was roadkilled by '
deathregex[25]='((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] was blown up by '
deathregex[26]='was shot in the (?:leg|arm|torso|head) by ((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\]!'
deathregex[27]='was chopped in the (?:leg|arm|torso|head) by ((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\]!'
deathregex[28]='was punched in the (?:leg|arm|torso|head) by ((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\]!'
deathregex[29]='was roadkilled by ((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\]!'
deathregex[30]='was blown up by ((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,}) \[((?:[A-Za-z]|[0-9]| |\.|\-|\:|\*|_|\[|\]|\<|\>|\^|\(|\)){1,})\] with (?:a|an) (?:grenade|missile|remote detonator|explosive bullet)!'
